version: "3.7"

services:
  # Define o serviço do Zattar Dashboard
  zattar-dashboard:
    # Usa imagem Node.js 20 Alpine
    image: node:20-alpine
    # Define o diretório de trabalho
    working_dir: /app
    # Define o comando otimizado
    command: |
      sh -c "
        apk add --no-cache git curl &&
        git clone https://github.com/Karllosmartins/zattar-dashboard.git . &&
        npm ci --only=production &&
        npm install --save-dev typescript @types/node tailwindcss postcss autoprefixer &&
        npm run build &&
        npm start
      "
    # Define a rede que o container vai usar
    networks:
      - network_swarm_public
    deploy:
      # Define o modo de deploy do container
      mode: replicated
      # Define o número de replicas do container (sempre 1)
      replicas: 1
      # Define o local de execução do container
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          # Recursos aumentados para build
          cpus: "1"
          memory: 1024M
      labels:
        # Habilita o Traefik
        - traefik.enable=true
        # Define o endereço público do Dashboard
        - traefik.http.routers.zattar_dashboard.rule=Host(`dashzattar.mysellers.com.br`)
        # Redireciona o endereço para HTTPS
        - traefik.http.routers.zattar_dashboard.entrypoints=websecure
        # Define o certificado SSL
        - traefik.http.routers.zattar_dashboard.tls.certresolver=letsencryptresolver
        # Define a porta do servidor do Dashboard
        - traefik.http.services.zattar_dashboard.loadbalancer.server.port=3000
        # Define os Headers que o Dashboard vai usar
        - traefik.http.services.zattar_dashboard.loadbalancer.passHostHeader=true
        # Define o serviço que irá ser usado
        - traefik.http.routers.zattar_dashboard.service=zattar_dashboard

# Definição dos Network do Stack
networks:
  network_swarm_public:
    external: true
    name: network_swarm_public