version: '3.8'

services:
  zattar-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zattar.rule=Host(`dashzattar.mysellers.com.br`)"
      - "traefik.http.routers.zattar.tls=true"
      - "traefik.http.routers.zattar.tls.certresolver=letsencrypt"
      - "traefik.http.services.zattar.loadbalancer.server.port=3000"
    networks:
      - web

networks:
  web:
    external: true