version: '3.8'

services:
  zattar-dashboard:
    image: node:18-alpine
    working_dir: /app
    command: |
      sh -c "
        apk add --no-cache git &&
        git clone https://github.com/Karllosmartins/zattar-dashboard.git . &&
        npm install &&
        npm run build &&
        npm start
      "
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure